spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_keeper?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Ima/1b8zKiIsT0wHShHWiAH5m9iHxJTkFCKiRUnve4i4n8blFjJaNuE2PfnEtot/mfrfvhHcuJjcm4sa5U1wpQ==
    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKcOdAgLcEa5CdiFLYz1cH7lb8zw8iyzRjgEpJnV+L2D1Gv5rkm7YkNHL607T81FiJdvYTZd2wwQ9ZZJqExLT+kCAwEAAQ==

weapon:
  common:
    redis:
      client-map:
        default:
          mode: SINGLE
          connection-pool-size: 200
          password: xmjjyhy28p
          address: 127.0.0.1:6379
          db: 1

app:
  security:
    client:
      appId: security-keeper
      appSecret: 123456
      serverURL: http://localhost:8080/
      allow-origin: http://localhost:9000
    filter:
      excludePatterns:
        - api/security/*
        - api/health/*
        - favicon.ico
  server:
    name: security_keeper_server
    aspectLogFile: ./log/aspect/web.log
    jwtConfig:
      secretHS256: JWT_%x6xo7l7_u9bf_u!9#g#m*)*=ej@bek8)(@u3kh*84+unjv=