spring:
  application:
    name: security-keeper-server
  profiles:
    active: @profileActive@
  server: 8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 3
      max-active: 100
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      filters: stat,wall,slf4j,config