spring:
  datasource:
    url: jdbc:mysql://rm-bp1jzevz9n51nnybryo.mysql.rds.aliyuncs.com:3306/hylian?useUnicode=true&characterEncoding=utf-8
    username: frankcl
    password: ${weapon/mysql/password}
    druid:
      public-key: ${weapon/mysql/public-key}
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${spring.datasource.druid.public-key}

weapon:
  common:
    etcd:
      client:
        username: root
        password: xmjjyhy28p
        endpoints:
          - http://localhost:2379
    redis:
      client:
        mode: single
        connection-pool-size: 200
        password: ${weapon/redis/password}
        address: localhost:6379
        db: 0
  aliyun:
    oss:
      client:
        endpoint: https://oss-cn-hangzhou-internal.aliyuncs.com
        socket-timeout-ms: 3000
        connection-timeout-ms: 3000
        retry-cnt: 3
hylian:
  client:
    appId: f733a689783eee56ad79886de1012699
    appSecret: oSUf9lwQ

app:
  server:
    aspectLogFile: ./log/aspect/web.log
    oss-region: cn-hangzhou
    oss-bucket: lumy
    oss-base-directory: hylian/prod
    default-tenant: e9c2227a9d7da6c1241b8c6782061b7f
    wx-version: develop
    mini-version: developer
    wechat-notice-new-user: 8BQJJagGrk2G8bwUZJ0p4v8xr3uXpCyut-B1U2pHAVw
    wechat-notice-user-audit: B4E0XRqlSC3Nnc70NPTDxHAUVZl-iAPmvAZh-x2DvNs